// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "8fdbb9d3-3ee6-4d4d-a714-d7ceb70d16bf";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

bool fireAlert1;
bool gasAlert1;
bool personAlert1;
void onResetChange(); 
CloudSwitch reset; 


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(fireAlert1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gasAlert1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(personAlert1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset, READWRITE, ON_CHANGE, onResetChange);
 
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
