// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "48a336c5-e2e6-4b61-bd1f-5d0f6ef890f2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onBurnerStateChange();

float roomTemp1;
int humidity1;
int burningRate1;
int burnerState;


void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  
  ArduinoCloud.addProperty(roomTemp1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(burningRate1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(burnerState, READWRITE, ON_CHANGE, onBurnerStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
